# Generated by Django 5.1.15 on 2026-03-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_artesano'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_adquisicion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_ultima_adquisicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='notas_internas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_gramos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_referencia',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_objetivo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiempo_adquisicion_dias',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
