# Generated by Django 5.1.15 on 2026-08-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_remove_producto_proveedor_referencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='costo_adquisicion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_ultima_adquisicion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_objetivo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tiempo_adquisicion_dias',
        ),
    ]
