# Generated by Django 5.1.15 on 2026-03-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('pagado', 'Pagado'), ('enviado', 'Enviado'), ('finalizado', 'Finalizado'), ('pago_rechazado', 'Pago rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
