# Generated by Django 5.1.15 on 2026-03-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(default='Home principal', max_length=150)),
                ('activa', models.BooleanField(default=True)),
                ('intro_label', models.CharField(blank=True, default='Nuestra esencia', max_length=100)),
                ('intro_titulo', models.CharField(blank=True, max_length=255)),
                ('intro_texto_1', models.TextField(blank=True)),
                ('intro_texto_2', models.TextField(blank=True)),
                ('colecciones_label', models.CharField(blank=True, default='Colecciones', max_length=100)),
                ('colecciones_titulo', models.CharField(blank=True, max_length=255)),
                ('colecciones_texto', models.TextField(blank=True)),
                ('proceso_label', models.CharField(blank=True, default='Proceso', max_length=100)),
                ('proceso_titulo', models.CharField(blank=True, max_length=255)),
                ('proceso_1_titulo', models.CharField(blank=True, default='Selección', max_length=150)),
                ('proceso_1_texto', models.TextField(blank=True)),
                ('proceso_2_titulo', models.CharField(blank=True, default='Trabajo manual', max_length=150)),
                ('proceso_2_texto', models.TextField(blank=True)),
                ('proceso_3_titulo', models.CharField(blank=True, default='Curaduría final', max_length=150)),
                ('proceso_3_texto', models.TextField(blank=True)),
                ('banda_label', models.CharField(blank=True, default='Hecho en contexto', max_length=100)),
                ('banda_titulo', models.CharField(blank=True, max_length=255)),
                ('banda_texto', models.TextField(blank=True)),
                ('tienda_label', models.CharField(blank=True, default='Tienda', max_length=100)),
                ('tienda_titulo', models.CharField(blank=True, max_length=255)),
                ('tienda_texto', models.TextField(blank=True)),
                ('tienda_boton_texto', models.CharField(blank=True, default='Ver ubicación', max_length=100)),
                ('tienda_boton_url', models.CharField(blank=True, default='/ubicacion/', max_length=255)),
                ('instagram_label', models.CharField(blank=True, default='Instagram', max_length=100)),
                ('instagram_titulo', models.CharField(blank=True, max_length=255)),
                ('instagram_texto', models.TextField(blank=True)),
                ('instagram_boton_texto', models.CharField(blank=True, default='Ir a Instagram', max_length=100)),
                ('instagram_boton_url', models.CharField(blank=True, default='/instagram/', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
