# Generated by Django 5.1.15 on 2026-03-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_homecoleccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontenido',
            name='instagram_imagen_1',
            field=models.ImageField(blank=True, null=True, upload_to='web/home/instagram/'),
        ),
        migrations.AddField(
            model_name='homecontenido',
            name='instagram_imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='web/home/instagram/'),
        ),
        migrations.AddField(
            model_name='homecontenido',
            name='instagram_imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='web/home/instagram/'),
        ),
        migrations.AddField(
            model_name='homecontenido',
            name='instagram_imagen_4',
            field=models.ImageField(blank=True, null=True, upload_to='web/home/instagram/'),
        ),
        migrations.AddField(
            model_name='homecontenido',
            name='intro_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='web/home/intro/'),
        ),
        migrations.AddField(
            model_name='homecontenido',
            name='proceso_imagen_1',
            field=models.ImageField(blank=True, null=True, upload_to='web/home/proceso/'),
        ),
        migrations.AddField(
            model_name='homecontenido',
            name='proceso_imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='web/home/proceso/'),
        ),
        migrations.AddField(
            model_name='homecontenido',
            name='proceso_imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='web/home/proceso/'),
        ),
        migrations.AddField(
            model_name='homecontenido',
            name='tienda_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='web/home/tienda/'),
        ),
    ]
