# Generated by Django 5.1.15 on 2026-03-14 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('web', '0004_homecontenido_instagram_imagen_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecoleccion',
            name='coleccion_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_home', to='catalogo.coleccion'),
        ),
    ]
