# Generated by Django 5.1.15 on 2026-03-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_homecoleccion_coleccion_catalogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiapagina',
            name='contenido',
        ),
        migrations.AddField(
            model_name='historiapagina',
            name='bloque_2_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='web/historia/'),
        ),
        migrations.AddField(
            model_name='historiapagina',
            name='bloque_2_label',
            field=models.CharField(blank=True, default='Origen', max_length=100),
        ),
        migrations.AddField(
            model_name='historiapagina',
            name='bloque_2_texto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historiapagina',
            name='bloque_2_titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historiapagina',
            name='destacado_label',
            field=models.CharField(blank=True, default='Lo que nos mueve', max_length=100),
        ),
        migrations.AddField(
            model_name='historiapagina',
            name='destacado_texto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historiapagina',
            name='destacado_titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historiapagina',
            name='intro_label',
            field=models.CharField(blank=True, default='Nuestra historia', max_length=100),
        ),
        migrations.AddField(
            model_name='historiapagina',
            name='intro_texto_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historiapagina',
            name='intro_texto_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historiapagina',
            name='intro_titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
