# Generated by Django 5.1.15 on 2026-03-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_historiapagina_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontenido',
            name='destacados_label',
            field=models.CharField(blank=True, default='Productos destacados', max_length=100),
        ),
        migrations.AddField(
            model_name='homecontenido',
            name='destacados_texto',
            field=models.TextField(blank=True, default='Piezas elegidas para mostrar la identidad, materiales y carácter de Poppy.'),
        ),
        migrations.AddField(
            model_name='homecontenido',
            name='destacados_titulo',
            field=models.CharField(blank=True, default='Una selección representativa de la marca', max_length=255),
        ),
    ]
