# Generated by Django 5.1.15 on 2026-03-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_homecontenido_destacados_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoinfo',
            name='ubicacion_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='web/ubicacion/'),
        ),
        migrations.AddField(
            model_name='contactoinfo',
            name='ubicacion_texto',
            field=models.TextField(blank=True, default='Descubre el espacio físico de Poppy Cartagena y vive la marca de cerca.'),
        ),
        migrations.AddField(
            model_name='contactoinfo',
            name='ubicacion_titulo',
            field=models.CharField(blank=True, default='Visítanos en tienda', max_length=255),
        ),
    ]
