# Generated by Django 5.1.15 on 2026-03-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_contactoinfo_ubicacion_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoinfo',
            name='instagram_cta_texto',
            field=models.TextField(blank=True, default='Síguenos para descubrir nuevas piezas, historias y procesos detrás de cada objeto.'),
        ),
        migrations.AddField(
            model_name='contactoinfo',
            name='instagram_cta_titulo',
            field=models.CharField(blank=True, default='Explora más en nuestro perfil', max_length=255),
        ),
        migrations.AddField(
            model_name='contactoinfo',
            name='instagram_imagen_1',
            field=models.ImageField(blank=True, null=True, upload_to='web/instagram/'),
        ),
        migrations.AddField(
            model_name='contactoinfo',
            name='instagram_imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='web/instagram/'),
        ),
        migrations.AddField(
            model_name='contactoinfo',
            name='instagram_imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='web/instagram/'),
        ),
        migrations.AddField(
            model_name='contactoinfo',
            name='instagram_imagen_4',
            field=models.ImageField(blank=True, null=True, upload_to='web/instagram/'),
        ),
        migrations.AddField(
            model_name='contactoinfo',
            name='instagram_texto_pagina',
            field=models.TextField(blank=True, default='Descubre el universo visual de Poppy Cartagena: piezas, procesos, tienda y contexto.'),
        ),
        migrations.AddField(
            model_name='contactoinfo',
            name='instagram_titulo_pagina',
            field=models.CharField(blank=True, default='Síguenos en Instagram', max_length=255),
        ),
    ]
