# Generated by Django 5.1.15 on 2026-03-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artesano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='artesanos/')),
                ('region', models.CharField(blank=True, max_length=200)),
                ('tecnica', models.CharField(blank=True, max_length=200)),
                ('bio_corta', models.TextField(blank=True)),
                ('bio_larga', models.TextField(blank=True)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
